# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kush Labs
tagline:          'Some tech blog'
description:      'Some tech blog'
url:              http://kushlabs.github.io

author:
  name:           'Kush Varma'
  url:            https://twitter.com/iamkushvarma

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/kushlabs/
